owner: petebachant
name: clima-perf
title: CliMA performance
description: Tracking CliMA performance over time.
git_repo_url: https://github.com/petebachant/clima-perf

environments:
  main:
    path: envs/main.txt
    kind: uv-venv
    prefix: .calkit/venvs/main/.venv
    python: "3.14"
  analyze:
    path: envs/analyze.txt
    kind: uv-venv
    prefix: .calkit/venvs/analyze/.venv
    python: "3.14"
  bk:
    path: envs/bk.txt
    kind: uv-venv
    prefix: .calkit/venvs/bk/.venv
    python: "3.14"
  clima:
    kind: slurm
    host: clima.gps.caltech.edu

pipeline:
  stages:
    benchmark-amip:
      kind: sbatch
      script_path: scripts/run.sh
      environment: clima
      sbatch_options:
        - --gpus=1
        - --time=120
      iterate_over:
        - arg_name: date
          values:
            # - "2025-10-15" # Fails
            - "2025-11-01"
            - "2025-11-02"
            - "2025-11-03"
            - "2025-11-04"
            # - "2025-11-07" # Fails
            # - "2025-11-14" # Fails
            # - "2025-12-01" # Fails
            - "2025-12-06"
            - "2025-12-20"
            - "2025-12-27"
            # - "2026-01-01" # Fails
            # - "2026-01-06" # Fails
            - "2026-01-13"
      args:
        - "{date}"
      log_path: runs/amip/{date}/output.log
      inputs:
        - scripts/run.py
        - .calkit/env-locks/main/linux-64.txt
        - repos/ClimaCoupler.jl/toml/amip_progedmf_1m.toml
        - repos/ClimaCoupler.jl/config/atmos_configs/climaatmos_progedmf_1m.yml
        - repos/ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      outputs:
        - path: runs/amip/{date}/Manifest-v1.11.toml
          storage: git
        - path: runs/amip/{date}/repo-revs.json
          storage: git
    fetch-buildkite:
      kind: jupyter-notebook
      environment: bk
      notebook_path: notebooks/buildkite.ipynb
      always_run: true
      html_storage: git
      executed_ipynb_storage: git
      outputs:
        - path: buildkite
          delete_before_run: false
          storage: git
    analyze:
      kind: jupyter-notebook
      environment: analyze
      notebook_path: notebooks/analyze.ipynb
      html_storage: git
      executed_ipynb_storage: git
      inputs:
        - runs/amip
        - buildkite
      outputs:
        - path: results/amip.csv
          storage: git
        - path: figures/amip-sypd.png
          storage: git
        - path: figures/amip-sypd.json
          storage: git

figures:
  - path: figures/amip-sypd.json
    title: Flagship AMIP normalized SYPD
    description: Flagship AMIP benchmark (16 horiz. elem.) SYPD over time
      normalized by the start of performance tracking.
    stage: analyze

notebooks:
  - path: notebooks/analyze.ipynb
    title: Analysis
    description: Analyze and plot the flagship AMIP benchmark (16 horiz.
      elem.) SYPD over time.

showcase:
  - figure: figures/amip-sypd.json
