owner: petebachant
name: clima-perf
title: CliMA performance
description: Tracking CliMA performance over time.
git_repo_url: https://github.com/petebachant/clima-perf

environments:
  main:
    path: envs/main.txt
    kind: uv-venv
    prefix: .calkit/venvs/main/.venv
    python: "3.14"
  clima:
    kind: slurm
    host: clima.gps.caltech.edu

pipeline:
  stages:
    benchmark-amip:
      kind: sbatch
      script_path: scripts/run.sh
      environment: clima
      sbatch_options:
        - --gpus=1
        - --time=120
      iterate_over:
        - arg_name: date
          values:
            - "2025-10-01"
            - "2025-11-01"
            - "2025-11-14"
            - "2025-12-01"
            - "2025-12-06"
            - "2025-12-20"
            - "2025-12-27"
            - "2026-01-01"
            - "2026-01-10"
            - "2026-01-12"
      args:
        - "{date}"
      log_path: logs/benchmark-amip/{date}.log
      inputs:
        - scripts/run.py
        - .calkit/env-locks/main/linux-64.txt
        - repos/ClimaCoupler.jl/toml/amip_progedmf_1m.toml
        - repos/ClimaCoupler.jl/config/atmos_configs/climaatmos_progedmf_1m.yml
        - repos/ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      outputs:
        - path: envs/{date}/Manifest-v1.11.toml
          storage: git
        - path: envs/{date}/repo-revs.json
          storage: git
    summarize:
      kind: python-script
      environment: main
      script_path: scripts/summarize.py
      inputs:
        - logs
      outputs:
        - path: results/summary.csv
          storage: git
