stages:
  benchmark-amip:
    cmd: calkit slurm batch --name benchmark-amip@${item.date} 
      --environment clima --log-path 
      'runs/amip/${item.date}/output.log' --dep scripts/run.py --dep 
      .calkit/env-locks/main/linux-64.txt --dep 
      repos/ClimaCoupler.jl/toml/amip_progedmf_1m.toml --dep 
      repos/ClimaCoupler.jl/config/atmos_configs/climaatmos_progedmf_1m.yml
      --dep 
      repos/ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      --out runs/amip/${item.date}/Manifest-v1.11.toml --out 
      runs/amip/${item.date}/repo-revs.json -s --gpus=1 -s --time=120 
      -- scripts/run.sh ${item.date}
    deps:
      - scripts/run.sh
      - scripts/run.py
      - .calkit/env-locks/main/linux-64.txt
      - repos/ClimaCoupler.jl/toml/amip_progedmf_1m.toml
      - repos/ClimaCoupler.jl/config/atmos_configs/climaatmos_progedmf_1m.yml
      - repos/ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
    outs:
      - runs/amip/${item.date}/Manifest-v1.11.toml:
          cache: false
          persist: true
      - runs/amip/${item.date}/repo-revs.json:
          cache: false
          persist: true
      - runs/amip/${item.date}/output.log:
          cache: false
          persist: true
    matrix:
      date:
        - '2025-11-01'
        - '2025-11-02'
        - '2025-11-03'
        - '2025-11-04'
        - '2025-12-06'
        - '2025-12-20'
        - '2025-12-27'
        - '2026-01-13'
    desc: Automatically generated from the 'benchmark-amip' stage in 
      calkit.yaml. Changes made here will be overwritten.
  fetch-buildkite:
    cmd: calkit nb execute --environment bk --no-check --language 
      python --to html "notebooks/buildkite.ipynb"
    deps:
      - .calkit/notebooks/cleaned/notebooks/buildkite.ipynb
      - .calkit/env-locks/bk
    outs:
      - buildkite:
          cache: false
          persist: true
      - .calkit/notebooks/executed/notebooks/buildkite.ipynb:
          cache: false
      - .calkit/notebooks/html/notebooks/buildkite.html:
          cache: false
    always_changed: true
    desc: Automatically generated from the 'fetch-buildkite' stage in 
      calkit.yaml. Changes made here will be overwritten.
  analyze:
    cmd: calkit nb execute --environment analyze --no-check --language
      python --to html "notebooks/analyze.ipynb"
    deps:
      - .calkit/notebooks/cleaned/notebooks/analyze.ipynb
      - runs/amip
      - buildkite
      - .calkit/env-locks/analyze
    outs:
      - results/amip.csv:
          cache: false
          persist: false
      - figures/amip-speedup.png:
          cache: false
          persist: false
      - figures/amip-speedup.json:
          cache: false
          persist: false
      - .calkit/notebooks/executed/notebooks/analyze.ipynb:
          cache: false
      - .calkit/notebooks/html/notebooks/analyze.html:
          cache: false
    desc: Automatically generated from the 'analyze' stage in 
      calkit.yaml. Changes made here will be overwritten.
